// Generated nations data from robotics-supply-chain-2026-v3/nations-verified.csv
// Auto-generated — do not hand-edit. Run the parse script to rebuild.
export interface NationData {
  count: number;
  indexes: string[];
  tier_a_count: number;
  slug: string;
  top_companies: { ticker: string; company: string; exchange: string; source: string }[];
}

export const nations: Record<string, NationData> = {
  "Sweden": {
    "count": 377,
    "indexes": ["Nasdaq Stockholm Large Cap", "Nasdaq Stockholm Mid Cap", "Nasdaq Stockholm Small Cap"],
    "tier_a_count": 1,
    "slug": "sweden",
    "top_companies": [
      { "ticker": "AAK.ST", "company": "AAK", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ABB.ST", "company": "ABB", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ALFA.ST", "company": "Alfa Laval", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ASSA-B.ST", "company": "Assa Abloy", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ATCO-A.ST", "company": "Atlas Copco", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "BOL.ST", "company": "Boliden", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ELUX-B.ST", "company": "Electrolux", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ERIC-B.ST", "company": "Ericsson", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "ESSITY-B.ST", "company": "Essity", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "HEXA-B.ST", "company": "Hexagon", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "SAND.ST", "company": "Sandvik", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
      { "ticker": "VOLV-B.ST", "company": "Volvo", "exchange": "Nasdaq Stockholm Large Cap", "source": "Yahoo" },
    ],
  },
  "Japan": {
    "count": 223,
    "indexes": ["Nikkei 225"],
    "tier_a_count": 13,
    "slug": "japan",
    "top_companies": [
      { "ticker": "2002.T", "company": "Nisshin Seifun Group", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "2269.T", "company": "Meiji Holdings", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "2282.T", "company": "NH Foods", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "2502.T", "company": "Asahi Group Holdings", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "2802.T", "company": "Ajinomoto", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "3402.T", "company": "Toray Industries", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "4063.T", "company": "Shin-Etsu Chemical", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "4543.T", "company": "Terumo", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "6501.T", "company": "Hitachi", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "6758.T", "company": "Sony Group", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "6954.T", "company": "Fanuc", "exchange": "Nikkei 225", "source": "Yahoo" },
      { "ticker": "6954.T", "company": "Fanuc", "exchange": "Nikkei 225", "source": "Yahoo" },
    ],
  },
  "Israel": {
    "count": 161,
    "indexes": ["TA-125", "TA-35"],
    "tier_a_count": 1,
    "slug": "israel",
    "top_companies": [
      { "ticker": "OPCE.TA", "company": "OPC Energy", "exchange": "TA-125", "source": "Yahoo" },
      { "ticker": "ORA.TA", "company": "Ormat Technologies", "exchange": "TA-125", "source": "Yahoo" },
      { "ticker": "ICL.TA", "company": "ICL Group", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "ESLT.TA", "company": "Elbit Systems", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "AMOT.TA", "company": "Amot Investments", "exchange": "TA-125", "source": "Yahoo" },
      { "ticker": "ENLT.TA", "company": "Enlight Energy", "exchange": "TA-125", "source": "Yahoo" },
      { "ticker": "DEDI.TA", "company": "Delek Drilling", "exchange": "TA-125", "source": "Yahoo" },
      { "ticker": "TEVA.TA", "company": "Teva Pharma", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "NICE.TA", "company": "NICE Ltd", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "CAMT.TA", "company": "Camtek", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "NVMI.TA", "company": "Nova Measuring", "exchange": "TA-35", "source": "Yahoo" },
      { "ticker": "TOWR.TA", "company": "Tower Semi", "exchange": "TA-35", "source": "Yahoo" },
    ],
  },
  "United Kingdom": {
    "count": 100,
    "indexes": ["FTSE 100"],
    "tier_a_count": 0,
    "slug": "united-kingdom",
    "top_companies": [
      { "ticker": "III.L", "company": "3i Group", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "ABDN.L", "company": "Abrdn", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "ADM.L", "company": "Admiral Group", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "AAF.L", "company": "Airtel Africa", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "ALW.L", "company": "Allied Witan", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "AAL.L", "company": "Anglo American", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "ANTO.L", "company": "Antofagasta", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "ASCL.L", "company": "Ascential", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "BATS.L", "company": "British American Tobacco", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "BARC.L", "company": "Barclays", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "BP.L", "company": "BP", "exchange": "FTSE 100", "source": "Yahoo" },
      { "ticker": "CCH.L", "company": "Coca-Cola HBC", "exchange": "FTSE 100", "source": "Yahoo" },
    ],
  },
  "Russia": {
    "count": 46,
    "indexes": ["MOEX (IMOEX)"],
    "tier_a_count": 0,
    "slug": "russia",
    "top_companies": [
      { "ticker": "LKOH.ME", "company": "Lukoil", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "SBER.ME", "company": "Sberbank", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "GAZP.ME", "company": "Gazprom", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "YDEX.ME", "company": "Yandex", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "TATN.ME", "company": "Tatneft", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "NVTK.ME", "company": "Novatek", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "ROSN.ME", "company": "Rosneft", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "CHMF.ME", "company": "Severstal", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "NLMK.ME", "company": "NLMK", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "MAGN.ME", "company": "MMK", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "ALRS.ME", "company": "Alrosa", "exchange": "MOEX", "source": "Yahoo" },
      { "ticker": "MTSS.ME", "company": "MTS", "exchange": "MOEX", "source": "Yahoo" },
    ],
  },
  "France": {
    "count": 40,
    "indexes": ["CAC 40"],
    "tier_a_count": 1,
    "slug": "france",
    "top_companies": [
      { "ticker": "AC.PA", "company": "Accor", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "AI.PA", "company": "Air Liquide", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "AIR.PA", "company": "Airbus", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "BNP.PA", "company": "BNP Paribas", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "CA.PA", "company": "Carrefour", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "CAP.PA", "company": "Capgemini", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "DSY.PA", "company": "Dassault Systèmes", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "ENGI.PA", "company": "Engie", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "MC.PA", "company": "LVMH", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "OR.PA", "company": "L'Oréal", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "SAN.PA", "company": "Sanofi", "exchange": "CAC 40", "source": "Yahoo" },
      { "ticker": "SU.PA", "company": "Schneider Electric", "exchange": "CAC 40", "source": "Yahoo" },
    ],
  },
  "Germany": {
    "count": 40,
    "indexes": ["DAX 40"],
    "tier_a_count": 3,
    "slug": "germany",
    "top_companies": [
      { "ticker": "ADS.DE", "company": "Adidas", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "ALV.DE", "company": "Allianz", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "BAS.DE", "company": "BASF", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "BAYN.DE", "company": "Bayer", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "BEI.DE", "company": "Beiersdorf", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "BMW.DE", "company": "BMW", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "DTE.DE", "company": "Deutsche Telekom", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "IFX.DE", "company": "Infineon", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "MBG.DE", "company": "Mercedes-Benz", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "SAP.DE", "company": "SAP", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "SIE.DE", "company": "Siemens", "exchange": "DAX 40", "source": "Yahoo" },
      { "ticker": "VOW3.DE", "company": "Volkswagen", "exchange": "DAX 40", "source": "Yahoo" },
    ],
  },
  "Spain": {
    "count": 35,
    "indexes": ["IBEX 35"],
    "tier_a_count": 0,
    "slug": "spain",
    "top_companies": [
      { "ticker": "ACS.MC", "company": "ACS", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "ACX.MC", "company": "Acerinox", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "AMS.MC", "company": "Amadeus", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "ANA.MC", "company": "Acciona", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "BBVA.MC", "company": "BBVA", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "CABK.MC", "company": "CaixaBank", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "ENG.MC", "company": "Enagás", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "FER.MC", "company": "Ferrovial", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "IBE.MC", "company": "Iberdrola", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "IDR.MC", "company": "Indra", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "ITX.MC", "company": "Inditex", "exchange": "IBEX 35", "source": "Yahoo" },
      { "ticker": "REP.MC", "company": "Repsol", "exchange": "IBEX 35", "source": "Yahoo" },
    ],
  },
  "Norway": {
    "count": 26,
    "indexes": ["OBX"],
    "tier_a_count": 0,
    "slug": "norway",
    "top_companies": [
      { "ticker": "AKRBP.OL", "company": "Aker BP", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "BAKKA.OL", "company": "Bakkafrost", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "BWLPG.OL", "company": "BW LPG", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "DNB.OL", "company": "DNB", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "DOFG.OL", "company": "DOF Group", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "EQNR.OL", "company": "Equinor", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "GJF.OL", "company": "Gjensidige", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "MOWI.OL", "company": "Mowi", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "NHY.OL", "company": "Norsk Hydro", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "ORK.OL", "company": "Orkla", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "SALM.OL", "company": "SalMar", "exchange": "OBX", "source": "Yahoo" },
      { "ticker": "TEL.OL", "company": "Telenor", "exchange": "OBX", "source": "Yahoo" },
    ],
  },
  "Finland": {
    "count": 25,
    "indexes": ["OMX Helsinki 25"],
    "tier_a_count": 0,
    "slug": "finland",
    "top_companies": [
      { "ticker": "ELISA.HE", "company": "Elisa", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "FORTUM.HE", "company": "Fortum", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "HIAB.HE", "company": "Hiab (Cargotec)", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "HUH1V.HE", "company": "Huhtamäki", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "KEMIRA.HE", "company": "Kemira", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "KNEBV.HE", "company": "Kone", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "METSB.HE", "company": "Metsä Board", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "NDA-FI.ST", "company": "Nordea", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "NESTE.HE", "company": "Neste", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "NOKIA.HE", "company": "Nokia", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "SAMPO.HE", "company": "Sampo", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
      { "ticker": "UPM.HE", "company": "UPM-Kymmene", "exchange": "OMX Helsinki 25", "source": "Yahoo" },
    ],
  },
  "Switzerland": {
    "count": 20,
    "indexes": ["SMI 20"],
    "tier_a_count": 1,
    "slug": "switzerland",
    "top_companies": [
      { "ticker": "NOVN.SW", "company": "Novartis", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "ROP.SW", "company": "Roche", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "NESN.SW", "company": "Nestlé", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "ABBN.SW", "company": "ABB", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "UBSG.SW", "company": "UBS Group", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "CFR.SW", "company": "Richemont", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "ZURN.SW", "company": "Zurich Insurance", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "SREN.SW", "company": "Swiss Re", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "GIVN.SW", "company": "Givaudan", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "LONN.SW", "company": "Lonza Group", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "SIGN.SW", "company": "SIG Combibloc", "exchange": "SMI 20", "source": "Yahoo" },
      { "ticker": "HOLN.SW", "company": "Holcim", "exchange": "SMI 20", "source": "Yahoo" },
    ],
  },
};

export const totalCompanies = 1093;
export const totalNations = 11;
export const verificationDate = '2026-08-30';

// Sorted nation list (highest count first)
export const nationList = Object.entries(nations)
  .sort(([, a], [, b]) => b.count - a.count)
  .map(([name, data]) => ({ name, ...data }));

// Country name mapping for Swedish
export const svNames: Record<string, string> = {
  'Sweden': 'Sverige',
  'Japan': 'Japan',
  'Israel': 'Israel',
  'United Kingdom': 'Storbritannien',
  'Russia': 'Ryssland',
  'France': 'Frankrike',
  'Germany': 'Tyskland',
  'Spain': 'Spanien',
  'Norway': 'Norge',
  'Finland': 'Finland',
  'Switzerland': 'Schweiz',
};